kind: Service
apiVersion: v1
metadata:  
  name: custom-ml-engine-service
  labels:
    name: custom-ml-engine
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31520

  selector:
    app: custom-ml-engine-deployment